stages:
  - deploy
  
deploy_dev:
    before_script:
      - sleep 10
      - ip a
      - sudo chmod 777 -R /home/gitlab-runner/
      - whoami
      - pwd
      - sudo chmod 777 -R /home/gitlab-runner/ 
      - sudo npm cache clean --force
      - sudo npm install -g serve
      - sudo npm install -g forever
      - sudo service uwsgi stop
    variables:
      GIT_STRATEGY: clone
    stage: deploy
    script:
      - whoami
      - pwd
      - sudo systemctl restart nginx
      - echo "Deploy to development server"
      - sleep 10 
      - sudo npm install
      - grep home package.json || true
      - export CI=false
      - export NODE_OPTIONS=--max_old_space_size=4096
      - export REACT_APP_UI_ENV=DEV
      - sudo -E bash -c "set \"CI=false\" &&  npm run build"
      - sudo rm -rf /home/ubuntu/build/
      - sudo cp -r build/ /home/ubuntu/
      - forever stop erp || true
      - forever start --uid "erp" -a -l forever.log -o out.log -e err.log $(which serve) -s /home/ubuntu/build -l 3000 
      - sonar-scanner   -Dsonar.projectKey=ERP-Revamp-User-Frontend   -Dsonar.sources=.   -Dsonar.host.url=http://3.6.23.199:9000   -Dsonar.login=40cf8e68959fee394596fa649b681f0f5875aef9 > sonar.log
      - cat sonar.log | grep -i browse
      - sudo service uwsgi start
    environment:
      name: erp_revamp_frontend
      url: 
    tags:
      - erp_revamp_frontend
    only:
      - dev
      - qa


deploy_prod:
    before_script:
      - sleep 10
      - ip a
      - sudo chmod 777 -R /home/gitlab-runner/
      - whoami
      - pwd
      - sudo chmod 777 -R /home/gitlab-runner/ 
      - sudo npm cache clean --force
      - sudo npm install -g serve
      - sudo npm install -g forever
    variables:
      GIT_STRATEGY: clone
    stage: deploy
    script:
      - whoami
      - pwd
      - sudo systemctl restart nginx
      - echo "Deploy to development server"
      - sleep 10 
      - sudo npm install
      - grep home package.json || true
      - export CI=false
      - export NODE_OPTIONS=--max_old_space_size=4096
      - export REACT_APP_UI_ENV=PROD
      - sudo -E bash -c "set \"CI=false\" &&  npm run build" || true
      - sudo rm -rf /home/ubuntu/build/
      - sudo cp -r build/ /home/ubuntu/
      - forever stopall
      - forever start -v --uid "erp" -a -l /var/log/frontend/forever.log -o /var/log/frontend/out.log -e /var/log/frontend/err.log $(which serve) -s /home/ubuntu/build -l 3000 
    environment:
      name: erp_revamp_frontend-prod
      url: 
    tags:
      - erp_revamp_frontend-prod
    only:
      - master
 
stages:
  - deploy

deploy_finance-integration2:
    before_script:
      - sleep 10
      - ip a
      - sudo chmod 777 -R /home/gitlab-runner/
      - whoami
      - pwd
      - sudo chmod 777 -R /home/gitlab-runner/ 
#      - sudo npm cache clean --force
      - sudo npm install -g serve
      - sudo npm install -g forever
    variables:
      GIT_STRATEGY: clone
    stage: deploy
    script:
      - whoami
      - pwd
      - sudo systemctl restart nginx
      - echo "Deploy to finance server"
      - sleep 10 
      - sudo npm install
      - sudo npm install
      - grep home package.json || true
      - export CI=false
      - sudo service uwsgi stop
      - export NODE_OPTIONS=--max_old_space_size=2048
      - sudo -E bash -c "set \"CI=false\" &&  npm run build"
      - sudo service uwsgi start
      - sudo rm -rf /home/ubuntu/finance-integration2/
      - sudo cp -r build/ /home/ubuntu/finance-integration2
      - forever stop finance-integration2 || true
      - forever start --uid "finance-integration2" -a -l forever.log -o out.log -e err.log $(which serve) -s /home/gitlab-runner/builds/hwUysH8D/0/k12devs1/erp-revamp-frontend/build -l 9005
#      - sonar-scanner   -Dsonar.projectKey=ERP-Revamp-User-Frontend   -Dsonar.sources=.   -Dsonar.host.url=http://3.6.23.199:9000   -Dsonar.login=40cf8e68959fee394596fa649b681f0f5875aef9 > sonar.log
#      - cat sonar.log | grep -i browse
    environment:
      name: finance-integration2
      url: 
    tags:
      - finance-integration2
    only:
      - finance-integration2

