export { default as AddQuestion } from './addQuestion'
export * from './EditQuestion'
export { default as AddChapter } from './addChapter'
export { default as ViewChapter } from './viewChapter'
export { default as UploadQuestionExcel } from './uploadQuestionExcel'
export { default as CreateAssessment } from './createAssessment'
export { default as ListQuestion } from './listQuestion'
export * from './questionPaper'
export { default as ListCompQuestion } from './listCompQues'
export * from './resultUpload'
export { default as dashboardQuestBox } from './dashboard'
export * from './assessment'
export * from './CreateTest'
