export * from './dashboard'
export * from './masters'
export * from './masterManagement'
export * from './teacherManagement'
export * from './manageTimeTable'
export * from './manageCalendar'
export * from './microScheduleLessonPlan'
export * from './questbox'
export * from './StudentReport'
export * from './studentCalender'
export * from './PracticeQuestion'
export { default as OnlineTest } from './Test'
export * from './attendance'
export * from './circular'
export * from './feeds'
export * from './id'
export * from './message'
export { default as SMS } from './sms'
export { default as Messaging } from './messaging'
export { default as Communication } from './communication'
export * from './Finance'
export * from './Inventory'
export * from './teacherlagreport'
export { default as CrashReport } from './internalTools/internalTools'
export * from './videoUpload'
export * from './results'
export * from './ClassGroup'
export * from './feedback'
export { default as Meal } from './Meal'
// eslint-disable-next-line import/export
export * from './academicPromotions'
export * from './emailSmsCommunication'
export { default as VideoPlayer } from './videoPlayer'
export { default as VideoSms } from './videoSms'
