import AdmissionFormAcc from './admissionForm'
import NewAdmissionFormAcc from './newAdmissionForm'
import CustomizedAdmissionFormAcc from './customizedAdmissionForm'
import StudentDetailsFormAcc from './studentDetails'
import StudentParentDetailsFormAcc from './studentParentDetails'
import AddressDetailsFormAcc from './addressDetails'
import OtherDetailsFormAcc from './otherDetails'
import NonRTEFormAcc from './nonRTEAdmissionForm'
import NonRTEStudentDetailsFormAcc from './nonRTEstudentDetails'
import NonRTEStudentParentDetailsFormAcc from './NonRTEStudentParentDetailsFormAcc'
import NonRTEAddressDetailsFormAcc from './nonRTEaddressDetails'
import NonRTEOtherDetailsFormAcc from './nonRTEotherDetails'
import UpdateAdmissionFormAcc from './updateAdmissionForm'
import UpdateStudentSiblingDetailsFormAcc from './updateStudentSiblingDetails'
import UpdateStudentCertiDetailsAcc from './updateStudentCertificateDetails'

export { AdmissionFormAcc, CustomizedAdmissionFormAcc, NewAdmissionFormAcc, StudentDetailsFormAcc, StudentParentDetailsFormAcc, AddressDetailsFormAcc, OtherDetailsFormAcc, NonRTEFormAcc, NonRTEStudentDetailsFormAcc, NonRTEStudentParentDetailsFormAcc, NonRTEAddressDetailsFormAcc, NonRTEOtherDetailsFormAcc, UpdateAdmissionFormAcc, UpdateStudentSiblingDetailsFormAcc, UpdateStudentCertiDetailsAcc as default }
